[package]
name = "governance-v2-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.governance-v2]
path = ".."

[dependencies.elrond-wasm-debug]
version = "=0.36.1"
